apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-backup-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongo-backup-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-backup-binding
subjects:
  - kind: ServiceAccount
    name: mongo-backup-sa
roleRef:
  kind: Role
  name: mongo-backup-role
  apiGroup: rbac.authorization.k8s.io
