apiVersion: v1
kind: Secret
metadata:
  name: mongo-backup-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://user:password@mongo-0.mongo-svc.default.svc.cluster.local:27017/?replicaSet=rs0"
  S3_ACCESS_KEY: "<your-arvan-access-key>"
  S3_SECRET_KEY: "<your-arvan-secret-key>"
